layout:
  name: example

config:
  rest_host: localhost
  rest_port: 8000
  kiosk_event_ws_uri: "ws://localhost:3000"
  kiosk_event_ws_timeout_secs: 30

camera_use:
  facial_recognition: "default"
  code_detection: "default"
  pill_detection_cam: "default"

models:
  face_detection: resources/models/yunet.onnx
  face_recognition: resources/models/sface.onnx
  pill_detector: resources/models/astromed.onnx
  pill_images_dir: resources/pill_images/
